#!/usr/bin/env python3
"""Generate the fixed RG34XX-SP launcher's embedded ROM catalogue."""

from __future__ import annotations

import argparse
import pathlib
import unicodedata


SYSTEMS = (
    ("SNES", (".zip", ".sfc", ".smc", ".fig", ".bs"), "RETROARCH"),
    ("PSP", (".cso", ".iso", ".pbp"), "PPSSPP"),
    ("Ports", (".sh",), "PORTMASTER"),
)


def c_string(value: str) -> str:
    encoded = value.encode("utf-8")
    output: list[str] = ['"']
    for byte in encoded:
        if byte == 34:
            output.append(r'\"')
        elif byte == 92:
            output.append(r"\\")
        elif 32 <= byte <= 126:
            output.append(chr(byte))
        else:
            output.append(f"\\{byte:03o}")
    output.append('"')
    return "".join(output)


def display_name(path: pathlib.Path) -> str:
    normalized = unicodedata.normalize("NFKD", path.stem)
    ascii_name = normalized.encode("ascii", "ignore").decode("ascii").upper()
    return " ".join(ascii_name.split()) or "UNTITLED"


def discover(
    rom_root: pathlib.Path, manifest: pathlib.Path | None
) -> list[tuple[str, str, str, list[tuple[str, str]]]]:
    requested: set[str] | None = None
    if manifest:
        requested = {
            line.strip()
            for line in manifest.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        }

    systems: list[tuple[str, str, str, list[tuple[str, str]]]] = []
    for directory, extensions, launcher in SYSTEMS:
        system_root = rom_root / directory
        entries: list[tuple[str, str]] = []
        if system_root.is_dir():
            for path in system_root.rglob("*"):
                if not path.is_file() or path.name.startswith("."):
                    continue
                if path.suffix.lower() not in extensions:
                    continue
                relative = path.relative_to(rom_root).as_posix()
                if requested is not None and relative not in requested:
                    continue
                entries.append((display_name(path), f"/mnt/mmc/ROMS/{relative}"))
        entries.sort(key=lambda entry: (entry[0], entry[1]))
        if entries:
            systems.append((directory, directory.upper(), launcher, entries))

    if requested is not None:
        discovered = {
            path.removeprefix("/mnt/mmc/ROMS/")
            for _directory, _name, _launcher, entries in systems
            for _display, path in entries
        }
        missing = sorted(requested - discovered)
        if missing:
            raise SystemExit("manifest entries missing or unsupported:\n" + "\n".join(missing))
    return systems


def render(systems: list[tuple[str, str, str, list[tuple[str, str]]]]) -> str:
    total = sum(len(system[3]) for system in systems)
    lines = [
        "/* Generated by generate-launcher-catalog.py; do not edit manually. */",
        "#ifndef DANI_CATALOG_GENERATED_H",
        "#define DANI_CATALOG_GENERATED_H",
        "",
        "#define CATALOG_LAUNCH_RETROARCH 1",
        "#define CATALOG_LAUNCH_PPSSPP 2",
        "#define CATALOG_LAUNCH_PORTMASTER 3",
        f"#define CATALOG_SYSTEM_COUNT {len(systems)}U",
        f"#define CATALOG_ENTRY_COUNT {total}U",
        "",
        "struct catalog_system {",
        "    const char *name;",
        "    u32 first;",
        "    u32 count;",
        "    u8 launch_kind;",
        "};",
        "",
        "struct catalog_entry {",
        "    const char *name;",
        "    const char *path;",
        "    u16 system;",
        "};",
        "",
        "static const struct catalog_system catalog_systems[CATALOG_SYSTEM_COUNT] = {",
    ]

    first = 0
    launch_constants = {
        "RETROARCH": "CATALOG_LAUNCH_RETROARCH",
        "PPSSPP": "CATALOG_LAUNCH_PPSSPP",
        "PORTMASTER": "CATALOG_LAUNCH_PORTMASTER",
    }
    for _directory, name, launcher, entries in systems:
        lines.append(
            f"    {{{c_string(name)}, {first}U, {len(entries)}U, {launch_constants[launcher]}}},"
        )
        first += len(entries)

    lines.extend(
        [
            "};",
            "",
            "static const struct catalog_entry catalog_entries[CATALOG_ENTRY_COUNT] = {",
        ]
    )
    for system_index, (_directory, _name, _launcher, entries) in enumerate(systems):
        for name, path in entries:
            lines.append(f"    {{{c_string(name)}, {c_string(path)}, {system_index}U}},")

    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("rom_root", type=pathlib.Path)
    parser.add_argument("--manifest", type=pathlib.Path)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=pathlib.Path(__file__).parent / "launcher" / "catalog.generated.h",
    )
    args = parser.parse_args()

    systems = discover(args.rom_root, args.manifest)
    if not systems:
        raise SystemExit(f"no supported ROMs found below {args.rom_root}")
    args.output.write_text(render(systems), encoding="utf-8", newline="\n")
    print(
        f"generated {sum(len(system[3]) for system in systems)} games "
        f"across {len(systems)} systems: {args.output}"
    )


if __name__ == "__main__":
    main()
