/* Generated by generate-launcher-catalog.py; do not edit manually. */
#ifndef DANI_CATALOG_GENERATED_H
#define DANI_CATALOG_GENERATED_H

#define CATALOG_LAUNCH_RETROARCH 1
#define CATALOG_LAUNCH_PPSSPP 2
#define CATALOG_LAUNCH_PORTMASTER 3
#define CATALOG_SYSTEM_COUNT 3U
#define CATALOG_ENTRY_COUNT 5U

struct catalog_system {
    const char *name;
    u32 first;
    u32 count;
    u8 launch_kind;
};

struct catalog_entry {
    const char *name;
    const char *path;
    u16 system;
};

static const struct catalog_system catalog_systems[CATALOG_SYSTEM_COUNT] = {
    {"SNES", 0U, 2U, CATALOG_LAUNCH_RETROARCH},
    {"PSP", 2U, 1U, CATALOG_LAUNCH_PPSSPP},
    {"PORTS", 3U, 2U, CATALOG_LAUNCH_PORTMASTER},
};

static const struct catalog_entry catalog_entries[CATALOG_ENTRY_COUNT] = {
    {"'96 ZENKOKU KOUKOU SOCCER SENSHUKEN (JAPAN)", "/mnt/mmc/ROMS/SNES/'96 Zenkoku Koukou Soccer Senshuken (Japan).zip", 0U},
    {"GOOF TROOP (USA)", "/mnt/mmc/ROMS/SNES/Goof Troop (USA).zip", 0U},
    {"GOD OF WAR - CHAINS OF OLYMPUS (USA)", "/mnt/mmc/ROMS/PSP/God of War - Chains of Olympus (USA).cso", 1U},
    {"MAX PAYNE", "/mnt/mmc/ROMS/Ports/Max Payne.sh", 2U},
    {"ROTA", "/mnt/mmc/ROMS/Ports/ROTA.sh", 2U},
};

#endif
