LABEL BIRD
  LINUX /bird-releases/v6.23/KERNEL
  INITRD /bird-releases/v6.23/bird-initramfs.cpio.gz
  FDT /bird-releases/v6.23/dtb.img
  APPEND boot=LABEL=BIRD disk=FILE=BIRD-STORAGE bird_release=v6.23 quiet fbcon=map:1 vt.global_cursor_default=0 panic=5
